import pathlib

configfile: "workflow/config.json"
include: "./rules/init.smk"
include: "./rules/common.smk"
include: "./rules/mrio_generation.smk"

ruleorder: generate_mrio_full_from_zip > mrio_sector_aggreg
ruleorder: mrio_sector_aggreg > mrio_one_region_RoW_aggreg

RUNS = [runs(xp) for folder, xp in xps.items()]
RUNS_PARQUET = [runs_from_parquet(xp) for folder, xp in xps.items()]

wildcard_constraints:
    run_type="raw|int",
    stype="Full|Subregions|RoW"

onstart:
     check_config(config)

#TODO : integrate interpolation script

#TODO : add cleaning script for record files

rule generate_csv_from_all_xp:
    """
    Generate csv file aggregating results from all experiences stated in config.json
    """
    input:
        csv_from_all_xp(xps)


rule generate_csv_from_xp:
    """
    Generate csv files for a specific experience.
    """
    input:
        xp_done = expand("{outputdir}/{{expdir}}/.experience_done", outputdir=config["OUTPUT_DIR"])
    output:
        expand("{outputdir}/{{expdir}}/{{run_type}}_{files}.csv", outputdir=config["OUTPUT_DIR"], files=["general", "prodloss","fdloss"]),
        touch(expand("{outputdir}/{{expdir}}/.{{run_type}}_experience_csv_done", outputdir=config["OUTPUT_DIR"]))
    conda:
        "env/boario-use.yml"
    params:
        dirs = expand("{outputdir}/{{expdir}}/", outputdir=config["OUTPUT_DIR"])
    resources:
        vmem_mb=500,
        mem_mb=500,
        disk_mb=500
    shell:
        """
        nice -n 10 python {config[INPUTS_GENERATION_SCRIPTS_DIR]}/csv_from_indicators.py {params.dirs} {wildcards.run_type} -o {input.dirs}
        """

rule xp_parquet:
    """
    Requires (invoke building rules for) all indicators files for an experience (specified by {expdir})
    """
    input:
        runs_from_folder
    output:
        touch(expand("{outputdir}/{{expdir}}/.experience_done", outputdir=config["OUTPUT_DIR"]))

rule all_xp_parquet:
    """
    Same as xp_parquet, but for all experiences in config.json
    """
    input:
        RUNS_PARQUET

rule test_parquet_from_full:
    """
    Run only a few simulation from all required simulations by config.json for testing purpose
    """
    input:
        RUNS_PARQUET[0][0:3]

rule indicators:
    """
    Build indicators and parquet results files for a specific simulation.
    """
    input:
        expand("{inp}/{{xp_folder}}/{{mrio_used}}/{{region}}_type_{{stype}}_qdmg_{{run_type}}_{{flood}}_Psi_{{psi}}_inv_tau_{{inv}}_inv_time_{{inv_t}}/{files}",
               inp=config["OUTPUT_DIR"],
               files=run_output_files)
    output:
        expand("{out}/{{xp_folder}}/{{mrio_used}}/{{region}}_type_{{stype}}_qdmg_{{run_type}}_{{flood}}_Psi_{{psi}}_inv_tau_{{inv}}_inv_time_{{inv_t}}/{files}",
               out=config["OUTPUT_DIR"],
               files=[
                   "indicators.json",
                   "treated_df_limiting.parquet",
                   "treated_df_loss.parquet",
                   "prod_df.parquet",
                   "io_demand_df.parquet",
                   "final_demand_df.parquet",
                   "prod_chg.json",
                   "fd_loss.json"])
    params:
        records=expand("{inp}/{{xp_folder}}/{{mrio_used}}/{{region}}_type_{{stype}}_qdmg_{{run_type}}_{{flood}}_Psi_{{psi}}_inv_tau_{{inv}}_inv_time_{{inv_t}}/{files}",
               inp=config["OUTPUT_DIR"],
               files=record_files)
    #group: "sim_run"
    conda:
        "env/boario-use.yml"
    resources:
        vmem_mb=indicators_get_vmem_mb,
        mem_mb=indicators_get_mem_mb,
        disk_mb=indicators_get_disk_mb
    shell:
        """
        cd {config[ARIO_DIR]};
        nice -n 10 python ./scripts/indicator_from_folder.py '{config[OUTPUT_DIR]}/{wildcards.xp_folder}/{wildcards.mrio_used}/{wildcards.region}_type_{wildcards.stype}_qdmg_{wildcards.run_type}_{wildcards.flood}_Psi_{wildcards.psi}_inv_tau_{wildcards.inv}_inv_time_{wildcards.inv_t}/';
        """

rule run_Full:
    """
    Run a "Full" simulation (no mrio region agregation or disagregation).

    run_inputs(wildcards) is in common.smk
    """
    input:
        unpack(run_inputs),
        event_template = lambda wildcards : get_event_template(wildcards.mrio_used,wildcards.xp_folder),
        mrio_params = lambda wildcards : get_mrio_params(wildcards.mrio_used,wildcards.xp_folder)
    output:
        record_files =  temp(expand("{out}/{{xp_folder}}/{{mrio_used}}/{{region}}_type_Full_qdmg_{{run_type}}_{{flood}}_Psi_{{psi}}_inv_tau_{{inv}}_inv_time_{{inv_t}}/{files}",
               out=config["OUTPUT_DIR"],
               files=record_files)),
        json_files = expand("{out}/{{xp_folder}}/{{mrio_used}}/{{region}}_type_Full_qdmg_{{run_type}}_{{flood}}_Psi_{{psi}}_inv_tau_{{inv}}_inv_time_{{inv_t}}/{files}",
                            out=config["OUTPUT_DIR"],
                            files=run_json_files)
    #group: "sim_run"
    params:
        output_dir = config["OUTPUT_DIR"]
    threads:
        4
    log:
        expand("{out}/{{xp_folder}}/{{mrio_used}}/{{region}}_type_Full_qdmg_{{run_type}}_{{flood}}_Psi_{{psi}}_inv_tau_{{inv}}_inv_time_{{inv_t}}/simulation.log",
               out=config["OUTPUT_DIR"])
    resources:
        vmem_mb=run_Full_get_vmem_mb,
        mem_mb=run_Full_get_mem_mb,
        disk_mb=run_Full_get_disk_mb
    wildcard_constraints:
        region="[A-Z]{2}"
    conda:
        "env/boario-use.yml"
    shell:
        """
        cd {config[ARIO_DIR]};
        nice -n 10 python ./scripts/mono_run.py {wildcards.region} {input.params_template} {wildcards.psi} {wildcards.inv} Full {wildcards.run_type} {wildcards.flood} {input.mrio} {params.output_dir}/{wildcards.xp_folder}/{wildcards.mrio_used} {input.flood_gdp} {input.event_template} {input.mrio_params} {wildcards.inv_t}
        """

rule run_subregions_mrio:
    """
    Run simulation where one region has been cut in subregions.
    (Probably deprecated)
    """
    input:
        unpack(run_inputs)
    output:
        expand("{out}/{{xp_folder}}/{{mrio_used}}/{{region}}_type_Subregions_qdmg_{{run_type}}_{{flood}}_Psi_{{psi}}_inv_tau_{{inv}}_inv_time_{{inv_t}}/{files}",
               out=config["OUTPUT_DIR"],
               files=run_output_files)
    params:
        output_dir = config["OUTPUT_DIR"],
        event_template = lambda wildcards : get_event_template(wildcards.mrio_used,wildcards.xp_folder),
        mrio_params = lambda wildcards : get_mrio_params(wildcards.mrio_used,wildcards.xp_folder)
    threads:
        8
    resources:
        vmem_mb=3000,
        mem_mb=2000,
        disk_mb=500
    wildcard_constraints:
        region="(?:[A-Z]{2}-[A-Z]{2}\d+)|([A-Z]{2}-all)",
        mrio_used="exiobase3_(?:Full|\d+_sectors)_(?:FullWorld|[A-Z]{2}-RoW)_[A-Z]{2}_sliced_in_\d+"
    conda:
        "env/boario-use.yml"
    params:
        output_dir = config["OUTPUT_DIR"],
    shell:
        """
        cd {config[ARIO_DIR]};
        nice -n 10 python ./scripts/mono_run.py {wildcards.region} {input.params_template} {wildcards.psi} {wildcards.inv} Full {wildcards.run_type} {wildcards.flood} {input.mrio} {params.output_dir}/{wildcards.xp_folder}/{wildcards.mrio_used} {input.flood_gdp} {params.event_template} {params.mrio_params} {wildcards.inv_t}
        """

rule run_RoW:
    """
    Run 'Rest of the World' simulation, where all regions expect the chosen one are agregated into a RoW region. (For testing/sensitivity purpose, might be broken at the moment)
    """
    input:
        unpack(run_RoW_inputs)
    output:
        expand("{out}/{{xp_folder}}/{{mrio_used}}/{{region}}_type_RoW_qdmg_{{run_type}}_{{flood}}_Psi_{{psi}}_inv_tau_{{inv}}_inv_time_{{inv_t}}/{files}",
               out=config["OUTPUT_DIR"],
               files=run_output_files)
    conda:
        "env/boario-use.yml"
    wildcard_constraints:
        run_type="raw|int"
    resources:
        mem_mb=4000,
        disk_mb=50,
        vmem_mb=4000
    params:
        ario_dir = config["ARIO_DIR"],
        output_dir = config["OUTPUT_DIR"],
    shell:
        """
        cd {params.ario_dir};
        nice -n 10 python ./scripts/mono_run.py {wildcards.region} {input.params_template} {wildcards.psi} {wildcards.inv} RoW {wildcards.run_type} {wildcards.flood} {input.mrio} {params.output_dir}/{wildcards.xp_folder}/{wildcards.mrio_used} {input.flood_gdp} {input.event_template} {input.mrio_params} {wildcards.inv_t}
        """
